In [1]:
# installing pandas library for dataframe manipulation analysis

In [2]:
import pandas as pd

In [3]:
# Loading up a dataset ('stock prices dataset.csv')

In [4]:
df = pd.read_csv('stock prices dataset.csv')
print(df)

       symbol        date      open      high       low     close    volume
0         AAL  2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943
1        AAPL  2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957
2         AAP  2014-01-02  110.3600  111.8800  109.2900  109.7400    542711
3        ABBV  2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061
4         ABC  2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391
...       ...         ...       ...       ...       ...       ...       ...
497467    XYL  2017-12-29   68.5300   68.8000   67.9200   68.2000   1046677
497468    YUM  2017-12-29   82.6400   82.7100   81.5900   81.6100   1347613
497469    ZBH  2017-12-29  121.7500  121.9500  120.6200  120.6700   1023624
497470   ZION  2017-12-29   51.2800   51.5500   50.8100   50.8300   1261916
497471    ZTS  2017-12-29   72.5500   72.7600   72.0400   72.0400   1704122

[497472 rows x 7 columns]

In [5]:
# Checking of data structure

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497472 entries, 0 to 497471
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   symbol  497472 non-null  object
 1   date    497472 non-null  object
 2   open    497461 non-null  float64
 3   high    497464 non-null  float64
 4   low     497464 non-null  float64
 5   close   497472 non-null  float64
 6   volume  497472 non-null  int64
dtypes: float64(4), int64(1), object(2)
memory usage: 26.6+ MB

In [7]:
# Preview of dataset

In [8]:
df.head()

  symbol        date      open      high       low     close    volume
0    AAL  2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943
1   AAPL  2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957
2    AAP  2014-01-02  110.3600  111.8800  109.2900  109.7400    542711
3   ABBV  2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061
4    ABC  2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391

In [9]:
# Let's check for missing values in the dataset

In [10]:
df.isnull().sum()

symbol     0
date       0
open      11
high       8
low        8
close      0
volume     0
dtype: int64

In [11]:
# Let's remove rows with missings value

In [12]:
df = df.dropna()

In [13]:
# Let's check the duplicates row in the dataset

In [14]:
df.duplicated().sum()

np.int64(0)

In [36]:
df['symbol'].value_counts().reset_index()

    symbol  count
0      ZTS   1007
1        A   1007
2      AAL   1007
3      AAP   1007
4     AAPL   1007
..     ...    ...
500    DXC    189
501   BHGE    126
502    BHF    116
503   DWDP     83
504   APTV     18

[505 rows x 2 columns]

In [16]:
# Let's Standardise the date format into datatime format

In [17]:
df.loc[:, 'date'] = pd.to_datetime(df['date'])

In [18]:
# Let us sort the dataset

In [19]:
df = df.sort_values(by=['symbol','date'])

In [20]:
# Let' reset the index

In [21]:
df.reset_index(drop=True, inplace=True)

In [22]:
# checking of dataset if its ready for analysis

In [23]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497461 entries, 0 to 497460
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   symbol  497461 non-null  object
 1   date    497461 non-null  object
 2   open    497461 non-null  float64
 3   high    497461 non-null  float64
 4   low     497461 non-null  float64
 5   close   497461 non-null  float64
 6   volume  497461 non-null  int64
dtypes: float64(4), int64(1), object(2)
memory usage: 26.6+ MB

,open,high,low,close,volume
count,497461.000000,497461.000000,497461.000000,497461.000000,4.974610e+05
mean,86.352275,87.132717,85.552616,86.368586,4.253695e+06
std,101.471228,102.312340,100.571231,101.471516,8.232210e+06
min,1.620000,1.690000,1.500000,1.590000,1.010000e+02
25%,41.690000,42.090000,41.280000,41.700000,1.080183e+06
50%,64.970000,65.560000,64.357400,64.980000,2.085013e+06
75%,98.410000,99.230000,97.580000,98.420000,4.271999e+06
max,2044.000000,2067.990000,2035.110000,2049.000000,6.182376e+08

In [24]:
df.head(100)

   symbol                 date   open    high     low  close   volume
0       A  2014-01-02 00:00:00  57.10  57.100  56.150  56.21  1916160
1       A  2014-01-03 00:00:00  56.39  57.345  56.260  56.92  1866651
2       A  2014-01-06 00:00:00  57.40  57.700  56.560  56.64  1777472
3       A  2014-01-07 00:00:00  56.95  57.630  56.930  57.45  1463208
4       A  2014-01-08 00:00:00  57.33  58.540  57.170  58.39  2659468
..    ...                  ...    ...     ...     ...    ...      ...
95      A  2014-05-20 00:00:00  54.87  54.960  54.209  54.31  1840126
96      A  2014-05-21 00:00:00  54.58  55.140  54.440  54.99  1102300
97      A  2014-05-22 00:00:00  55.00  55.710  54.890  55.54  1686139
98      A  2014-05-23 00:00:00  55.65  56.220  55.175  56.18  3510829
99      A  2014-05-27 00:00:00  56.31  56.500  56.030  56.28  1190619

[100 rows x 7 columns]

In [37]:
df.tail(100)

       symbol                 date   open   high    low  close   volume
497361    ZTS  2017-08-09 00:00:00  59.95  60.87  59.76  60.81  4017297
497362    ZTS  2017-08-10 00:00:00  60.87  61.37  59.71  59.74  2690725
497363    ZTS  2017-08-11 00:00:00  60.05  60.22  59.64  59.73  2285863
497364    ZTS  2017-08-14 00:00:00  60.19  60.83  60.04  60.74  2475394
497365    ZTS  2017-08-15 00:00:00  60.86  61.68  60.56  61.03  2220781
...       ...                  ...    ...    ...    ...    ...      ...
497456    ZTS  2017-12-22 00:00:00  72.30  72.37  71.79  71.99  1345683
497457    ZTS  2017-12-26 00:00:00  72.40  72.55  71.90  72.34   792134
497458    ZTS  2017-12-27 00:00:00  72.59  72.69  72.25  72.45  1159771
497459    ZTS  2017-12-28 00:00:00  72.49  72.60  72.14  72.39   710499
497460    ZTS  2017-12-29 00:00:00  72.55  72.76  72.04  72.04  1704122

[100 rows x 7 columns]

In [26]:
# filter of close position exactly 200.38

In [27]:
df.query('close ==200.38')

       symbol                 date    open     high     low   close   volume
2476      AAP  2015-11-02 00:00:00  199.14  201.170  197.98  200.38   728521
34422     AMG  2014-09-25 00:00:00  203.59  203.715  200.00  200.38   265217
95306    CHTR  2016-04-11 00:00:00  203.30  203.745  200.16  200.38   911749
302821    MHK  2015-09-03 00:00:00  198.68  201.550  198.30  200.38   667441
348553   ORLY  2017-09-05 00:00:00  197.72  202.389  197.72  200.38  1042302
348555   ORLY  2017-09-07 00:00:00  202.63  203.420  198.50  200.38   887671
476498    WHR  2015-04-02 00:00:00  200.00  201.670  199.26  200.38   821889

In [28]:
# highest profits in each stock

In [29]:
df.groupby('symbol')['close'].max().reset_index()

    symbol   close
0        A   70.59
1      AAL   55.76
2      AAP  200.38
3     AAPL  176.42
4     ABBV   98.21
..     ...     ...
500    XYL   69.34
501    YUM   94.88
502    ZBH  133.09
503   ZION   51.74
504    ZTS   72.80

[505 rows x 2 columns]

In [30]:
df.groupby('symbol')['close'].sum().reset_index()

    symbol        close
0        A   49441.4100
1      AAL   42721.8746
2      AAP  144189.4300
3     AAPL  117657.7717
4     ABBV   63781.6700
..     ...          ...
500    XYL   43819.8350
501    YUM   76937.0300
502    ZBH  111361.0100
503   ZION   32903.2650
504    ZTS   47599.1580

[505 rows x 2 columns]

In [31]:
df.groupby('symbol')['close'].mean().reset_index()

    symbol       close
0        A   49.097726
1      AAL   42.424900
2      AAP  143.187120
3     AAPL  116.839892
4     ABBV   63.338302
..     ...         ...
500    XYL   43.515228
501    YUM   76.402214
502    ZBH  110.586902
503   ZION   32.674543
504    ZTS   47.268280

[505 rows x 2 columns]

In [32]:
df.iloc[2476].reset_index()

    index                 2476
0  symbol                  AAP
1    date  2015-11-02 00:00:00
2    open               199.14
3    high               201.17
4     low               197.98
5   close               200.38
6  volume               728521